version: '3'

services:
  app:
    image: jboss/keycloak:15.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      #- KEYCLOAK_IMPORT=/tmp/test-realm-export.json
      - DB_VENDOR=h2
    ports:
      - 8080:8080