version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:3306 ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: ./.docker/mysql
    tty: true
    volumes: 
      - './.docker/dbdata:/var/lib/mysql'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root